<a href="https://colab.research.google.com/github/Indrajeet71/tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.11.0


In [ ]:
#create tensors with tf.constants()
scalar=tf.constant(7)
scalar
 

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of tensor(ndim stands for number of dimensions)
scalar.ndim


0

In [ ]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#create dimension of the vector
vector.ndim

1

In [ ]:
#create a matrix
matrix=tf.constant([[1,2],
                   [2,1]])
matrix
      

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 1]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
a_matrix=tf.constant([[10.,7.],
                      [3.,5.]],dtype=tf.float16)#specfy data type here
a_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  5.]], dtype=float16)>

In [ ]:
a_matrix.ndim

2

In [ ]:
#create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]],
                   [[13,14,15],
                    [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

scalar : a single number
vector : a number with direction
matrix : a 2-d dimension array of numbers
tensor : a n-dimensonal array of numbers(when n can be any number,a 0-dimensional tensor is scalar,a 1-dimensional tensor is vector)

creating tensorflow with tf.variable


In [ ]:
#create
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# to change one of the tensor (use .assign)
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

Create Random Tensors


In [ ]:
 #create two random but same tensors
 random=tf.random.Generator.from_seed(42)
 random=random.normal(shape=(3,2))
 random


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

shuffle tensors

In [ ]:
non_shuffled=tf.constant([[1,2],
                          [3,4],
                          [5,6]])
#to shuffle oue tensor
tf.random.shuffle(non_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
#using seed
tf.random.set_seed(32)
tf.random.shuffle(non_shuffled,seed=32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

other ways to make tensors

In [ ]:
#create with tf.ones (creates a tensor with all elments set to one(1))
tf.ones([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create with tf.zeros
tf.zeros(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

numpy arrays to tensors

* main differnece between numpy array and tensors,is that tensors can run on gpu

In [ ]:
#you can turn numpy arrays into tensors
import numpy as np
np_A=np.arange(2, 10,dtype=np.int32)
np_A

array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
#to convert np_A into tensor A
A=tf.constant(np_A,shape=(2,2,2))
A


<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]], dtype=int32)>

Getting info from tensor

Attributes of tensors
*shape (tf.shape)
*rank  (tf.ndim)
*axis or dimension (tf[0],tf[:,1]..)
*Size (tf.size(tensor))


In [ ]:
#create rank for tensor
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor



<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0] #getting axis

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape# getting shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor.ndim #getting rank

4

In [ ]:
tf.size(rank_4_tensor)#getting size

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
#get various attributes of tensor
print("Datatype of every element:",rank_4_tensor.dtype)
#get shape,ndim,

Datatype of every element: <dtype: 'float32'>


Indexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
#Get the first 2 ekementsof each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get first element from each dimension except for the last one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor=tf.constant([[1,2],
                           [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
rank_2_tensor.ndim

2

In [ ]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# alternative tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)# "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

Manipulating Tensors
Basic opration

In [ ]:
#Add values to a tensor
tensor=tf .constant([[1,2],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# to change original tensor
tensor=tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplicaiton
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [ ]:
#subtraction
tensor-10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# we can use build-in function
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [ ]:
tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 22],
       [23, 24]], dtype=int32)>

In [ ]:
tf.math.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

Matrix Multiplication

In [ ]:
 A=tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])
 B=tf.constant([[7,8,9],
                 [1,2,3],
                  [4,5,6]])

In [ ]:
A,B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[7, 8, 9],
        [1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

for matrix multiplication  use tf.amtmul

In [ ]:
tf.matmul(A,B)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 21,  27,  33],
       [ 57,  72,  87],
       [ 93, 117, 141]], dtype=int32)>

In [ ]:
A*B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7, 16, 27],
       [ 4, 10, 18],
       [28, 40, 54]], dtype=int32)>

In [ ]:
# matrix multiplication with python operator "@"
A @ B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 21,  27,  33],
       [ 57,  72,  87],
       [ 93, 117, 141]], dtype=int32)>

In [ ]:
  # change shape of B
  tf.reshape(B,shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

# we can also use tf.transpose() instead of reshape
 
 and also with 
 tf,matmul()
 tf.tensordot()

In [ ]:
tf.tensordot(tf.transpose(A),B,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[39, 51, 63],
       [51, 66, 81],
       [63, 81, 99]], dtype=int32)>

In [ ]:
#perform matrix multiplication between X and Y(transposed)
tf.matmul(A,tf.transpose(B))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 50,  14,  32],
       [122,  32,  77],
       [194,  50, 122]], dtype=int32)>

In [ ]:
#perform matrix multiplication between A and B(reshaped)
tf.matmul(A,tf.reshape(B,shape=(3,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 21,  27,  33],
       [ 57,  72,  87],
       [ 93, 117, 141]], dtype=int32)>

In [ ]:
# check values of A ,reshape A and transpose A
print("Normal A : ")
print(A,"\n")
print("reshaped A :")
print(tf.reshape(A,(3,3)),"\n")
print("transposed A:")
print(tf.transpose(A))



Normal A : 
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 

reshaped A :
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 

transposed A:
tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)


Generally,when performing matrix multiplication on two tensors and one of the axes doesn;t line up,you will transpose (rather than reshape) one of the tensor to get satisfy the matrix multiplication rules.

CHanging the datatype of tensor


In [ ]:
S=tf.constant([1.2,3.4])
S.dtype

tf.float32

In [ ]:
C=tf.constant([2,3])
C.dtype

tf.int32

In [ ]:
#change float32 to float16
W=tf.cast(S,dtype=tf.float16)
W

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.4], dtype=float16)>

In [ ]:
#change int32 to float32
O=tf.cast(C,dtype=tf.float32)
O


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

**Aggregating tensors**
means considering them from multiple values down to smaller amount of values

In [ ]:
I=tf.constant([-6,-9])
I

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-6, -9], dtype=int32)>

In [ ]:
# Get absolute values
tf.abs(I)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 9], dtype=int32)>



1.  get minimum
2.   get maximum
3. get mean
4. get sum of tensor





In [ ]:
#create a tensor with values between 0 and 100 of size 50
W=tf.constant(np.random.randint(0,100,size=50))
W

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([80, 48, 58, 15, 27, 92, 97, 81, 80, 21, 38, 61, 34, 79, 49, 39, 84,
       65, 41, 73, 66, 12, 91, 79, 93, 14, 29, 26,  4, 29, 76, 85, 50, 99,
       98, 66,  5, 74, 79, 22, 16, 52, 78, 72, 88, 26, 67, 74, 66, 54])>

In [ ]:
#finf minimum
tf.reduce_min(W)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
#find max
tf.reduce_max(W)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#find mean
tf.reduce_mean(W)

<tf.Tensor: shape=(), dtype=int64, numpy=57>

In [ ]:
#find sum
tf.reduce_sum(W)

<tf.Tensor: shape=(), dtype=int64, numpy=2852>

In [ ]:
tf.math.reduce_variance(W)

TypeError: ignored

One-hot encoding tensors


In [ ]:
q=[0,1,2,3]
depth=4
#one-hot encode q
tf.one_hot(q,depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify one-hot encoding
tf.one_hot(q,depth,on_value="yo i love DL",off_value="I also hate it")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love DL', b'I also hate it', b'I also hate it',
        b'I also hate it'],
       [b'I also hate it', b'yo i love DL', b'I also hate it',
        b'I also hate it'],
       [b'I also hate it', b'I also hate it', b'yo i love DL',
        b'I also hate it'],
       [b'I also hate it', b'I also hate it', b'I also hate it',
        b'yo i love DL']], dtype=object)>

GPU

In [ ]:
tf.config.list_physical_devices()


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi # to check which gpu we using

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

